/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;
import com.itextpdf.text.Document;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Naome
 */
public class man_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form man_Dashboard
     */
    public man_Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RecordjPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        reportjPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        companyjPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ViewjPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ReportBTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bindpanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MANAGER'S DASHBOARD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 180, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 8));

        RecordjPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecordjPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RecordjPanel5MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("RECORD BUS");

        javax.swing.GroupLayout RecordjPanel5Layout = new javax.swing.GroupLayout(RecordjPanel5);
        RecordjPanel5.setLayout(RecordjPanel5Layout);
        RecordjPanel5Layout.setHorizontalGroup(
            RecordjPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecordjPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RecordjPanel5Layout.setVerticalGroup(
            RecordjPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(RecordjPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("REPORTS");

        javax.swing.GroupLayout reportjPanel6Layout = new javax.swing.GroupLayout(reportjPanel6);
        reportjPanel6.setLayout(reportjPanel6Layout);
        reportjPanel6Layout.setHorizontalGroup(
            reportjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportjPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        reportjPanel6Layout.setVerticalGroup(
            reportjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(reportjPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 30));

        companyjPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyjPanel7MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("COMPANIES");

        javax.swing.GroupLayout companyjPanel7Layout = new javax.swing.GroupLayout(companyjPanel7);
        companyjPanel7.setLayout(companyjPanel7Layout);
        companyjPanel7Layout.setHorizontalGroup(
            companyjPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyjPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        companyjPanel7Layout.setVerticalGroup(
            companyjPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, companyjPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(companyjPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, -1));

        ViewjPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewjPanel9MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("VIEW ALL BUSES ");

        javax.swing.GroupLayout ViewjPanel9Layout = new javax.swing.GroupLayout(ViewjPanel9);
        ViewjPanel9.setLayout(ViewjPanel9Layout);
        ViewjPanel9Layout.setHorizontalGroup(
            ViewjPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewjPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        ViewjPanel9Layout.setVerticalGroup(
            ViewjPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewjPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 8, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(ViewjPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, -1));

        ReportBTN.setText("Reports");
        ReportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportBTNActionPerformed(evt);
            }
        });
        jPanel2.add(ReportBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel7.setText("LOGOUT");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 470));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setText("KIMIRONKO BUS STATION");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 660, 50));

        bindpanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout bindpanelLayout = new javax.swing.GroupLayout(bindpanel);
        bindpanel.setLayout(bindpanelLayout);
        bindpanelLayout.setHorizontalGroup(
            bindpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        bindpanelLayout.setVerticalGroup(
            bindpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(bindpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 660, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecordjPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecordjPanel5MousePressed
        
    }//GEN-LAST:event_RecordjPanel5MousePressed

    private void RecordjPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecordjPanel5MouseClicked
       Busview busform=new Busview();
       bindpanel.removeAll();
       bindpanel.add(busform).setVisible(true);
      
    }//GEN-LAST:event_RecordjPanel5MouseClicked

    private void ViewjPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewjPanel9MouseClicked
       BusManagment form=new BusManagment();
       bindpanel.removeAll();
       bindpanel.add(form).setVisible(true);
    }//GEN-LAST:event_ViewjPanel9MouseClicked

    private void companyjPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyjPanel7MouseClicked
          Company Cform=new Company();
       bindpanel.removeAll();
       bindpanel.add(Cform).setVisible(true);
    }//GEN-LAST:event_companyjPanel7MouseClicked

    private void ReportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportBTNActionPerformed
 JFileChooser fileChooser = new JFileChooser("C:\\Users\\Naome\\Desktop\\Reports");
    fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    
    // Set a filter to show only PDF files
    FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF Files", "pdf");
    fileChooser.setFileFilter(filter);

    int result = fileChooser.showOpenDialog(this);
    
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        
        if (selectedFile.exists() && selectedFile.isFile()) {
            try {
                // Use the default system application to open the selected PDF file
                Desktop.getDesktop().open(selectedFile);
            } catch (IOException e) {
                e.printStackTrace();
                // Handle the case where an error occurs while opening the PDF file
            }
        } else {
            // Handle the case where the selected file does not exist
        }
    }

    }//GEN-LAST:event_ReportBTNActionPerformed

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
         login log=new login();
        log.setLocationRelativeTo(null);
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(man_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(man_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(man_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(man_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new man_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RecordjPanel5;
    private javax.swing.JButton ReportBTN;
    private javax.swing.JPanel ViewjPanel9;
    private javax.swing.JDesktopPane bindpanel;
    private javax.swing.JPanel companyjPanel7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel reportjPanel6;
    // End of variables declaration//GEN-END:variables
}
