/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author Naome
 */
public class supervisorDash extends javax.swing.JFrame {

     private routeMang routeForm;
    private BusScheduling busSchedulingForm;
    private ViewBuses viewBusesForm;
    private ReportsGen reportsGenForm;
     // Creates new form supervisorDash
     
    public supervisorDash() {
        initComponents();
        this.setLocationRelativeTo(null);
      routeForm = new routeMang();
        busSchedulingForm = new BusScheduling();
        viewBusesForm = new ViewBuses();
        reportsGenForm = new ReportsGen();

        // Add internal frames to the bind panel
        bindpanel.add(routeForm);
        bindpanel.add(busSchedulingForm);
        bindpanel.add(viewBusesForm);
        bindpanel.add(reportsGenForm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RecordjPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        reportjPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        companyjPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ViewjPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        bindpanel = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SUPERVISOR");
        setName("supervisorDash"); // NOI18N
        setPreferredSize(new java.awt.Dimension(920, 480));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SUPERVISOR'S DASHBOARD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 8));

        RecordjPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecordjPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RecordjPanel5MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("RECORD ROUTES AVAILABLE");

        javax.swing.GroupLayout RecordjPanel5Layout = new javax.swing.GroupLayout(RecordjPanel5);
        RecordjPanel5.setLayout(RecordjPanel5Layout);
        RecordjPanel5Layout.setHorizontalGroup(
            RecordjPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecordjPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RecordjPanel5Layout.setVerticalGroup(
            RecordjPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(RecordjPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, 30));

        reportjPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportjPanel6MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("REPORTS");

        javax.swing.GroupLayout reportjPanel6Layout = new javax.swing.GroupLayout(reportjPanel6);
        reportjPanel6.setLayout(reportjPanel6Layout);
        reportjPanel6Layout.setHorizontalGroup(
            reportjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportjPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        reportjPanel6Layout.setVerticalGroup(
            reportjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(reportjPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 30));

        companyjPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyjPanel7MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("BUS SCHEDULING");

        javax.swing.GroupLayout companyjPanel7Layout = new javax.swing.GroupLayout(companyjPanel7);
        companyjPanel7.setLayout(companyjPanel7Layout);
        companyjPanel7Layout.setHorizontalGroup(
            companyjPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyjPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        companyjPanel7Layout.setVerticalGroup(
            companyjPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, companyjPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(companyjPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, -1));

        ViewjPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewjPanel9MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("VIEW ALL BUSES ");

        javax.swing.GroupLayout ViewjPanel9Layout = new javax.swing.GroupLayout(ViewjPanel9);
        ViewjPanel9.setLayout(ViewjPanel9Layout);
        ViewjPanel9Layout.setHorizontalGroup(
            ViewjPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewjPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        ViewjPanel9Layout.setVerticalGroup(
            ViewjPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewjPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 8, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(ViewjPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, -1));

        logout.setText("LOGOUT");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 100, -1));

        bindpanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout bindpanelLayout = new javax.swing.GroupLayout(bindpanel);
        bindpanel.setLayout(bindpanelLayout);
        bindpanelLayout.setHorizontalGroup(
            bindpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        bindpanelLayout.setVerticalGroup(
            bindpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("BUS STATION MANAGMENT SYTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bindpanel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(bindpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecordjPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecordjPanel5MouseClicked
     // routeMang routeform=new routeMang();

        //bindpanel.removeAll();
       // bindpanel.add(routeform).setVisible(true);
         routeForm.setVisible(true);
        busSchedulingForm.setVisible(false);
        viewBusesForm.setVisible(false);
        reportsGenForm.setVisible(false);

    }//GEN-LAST:event_RecordjPanel5MouseClicked

    private void RecordjPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecordjPanel5MousePressed

    }//GEN-LAST:event_RecordjPanel5MousePressed

    private void companyjPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyjPanel7MouseClicked
        //BusScheduling bus=new BusScheduling();
        //bindpanel.removeAll();
        //bindpanel.add(bus).setVisible(true);
           routeForm.setVisible(false);
        busSchedulingForm.setVisible(true);
        viewBusesForm.setVisible(false);
        reportsGenForm.setVisible(false);
    }//GEN-LAST:event_companyjPanel7MouseClicked

    private void ViewjPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewjPanel9MouseClicked
        //ViewBuses form=new ViewBuses();
        //bindpanel.removeAll();
        //bindpanel.add(form).setVisible(true);
           routeForm.setVisible(false);
        busSchedulingForm.setVisible(false);
        viewBusesForm.setVisible(true);
        reportsGenForm.setVisible(false);
    }//GEN-LAST:event_ViewjPanel9MouseClicked

    private void reportjPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportjPanel6MouseClicked
       //ReportsGen form2=new ReportsGen();
       //bindpanel.removeAll();
       //bindpanel.add(form2).setVisible(true);
           routeForm.setVisible(false);
        busSchedulingForm.setVisible(false);
        viewBusesForm.setVisible(false);
        reportsGenForm.setVisible(true);
    }//GEN-LAST:event_reportjPanel6MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
     
      
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        login log=new login();
        log.setLocationRelativeTo(null);
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supervisorDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supervisorDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supervisorDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supervisorDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supervisorDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RecordjPanel5;
    private javax.swing.JPanel ViewjPanel9;
    private javax.swing.JDesktopPane bindpanel;
    private javax.swing.JPanel companyjPanel7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel reportjPanel6;
    // End of variables declaration//GEN-END:variables
}
